<?php
/**
 * CsnUser - Coolcsn Zend Framework 2 User Module
 * 
 * @link https://github.com/coolcsn/CsnUser for the canonical source repository
 * @copyright Copyright (c) 2005-2013 LightSoft 2005 Ltd. Bulgaria
 * @license https://github.com/coolcsn/CsnUser/blob/master/LICENSE BSDLicense
 * @author Stoyan Cheresharov <stoyan@coolcsn.com>
 * @author Svetoslav Chonkov <svetoslav.chonkov@gmail.com>
 * @author Nikola Vasilev <niko7vasilev@gmail.com>
 * @author Stoyan Revov <st.revov@gmail.com>
 * @author Martin Briglia <martin@mgscreativa.com>
 */

echo $this->partial('csn-user/layout/nav-menu', array('navMenu' => $this->navMenu, 'user' => $this->identity()));

?>

<div class="jumbotron">
<?php if($user = $this->identity()) { ?>
  <h1 style="float:left;">
    <?php echo $this->translate('Welcome', 'csnuser') ?>
    <a href="<?php echo $this->url('user-register', array('action' => 'edit-profile'));?>">
      <span class="zf-green"><?php echo $this->escapeHtml($user->getUsername()); ?></span>
    </a>
  </h1>
  <a href="<?php echo $this->url('user-index', array('action' => 'logout'));?>" class="btn btn-success btn-lg" style="float:right; margin-top: 25px">
    <?php echo $this->translate('Log Out', 'csnuser'); ?>
  </a>
  <div style="clear: both"></div>
  <div class="row">
    <?php echo $this->translate('Congratulations! You have successfully logged in.', 'csnuser') ?>
  </div>
<?php } else { ?>
  <h1><?php echo $this->translate('Welcome', 'csnuser') ?><span  style="color: #FF8C00"> <?php echo $this->translate('Guest', 'csnuser') ?></span>!</h1>
  <div>
    <?php echo $this->translate('Please follow the buttons at the top to navigate through the system.', 'csnuser') ?>
  </div>
<?php } ?>
</div>
